apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pipelines
kind: "Template"
apiVersion: "v1"
metadata:
  name: "jenkins-pipeline"
  annotations:
    openshift.io/display-name: "Jenkins (Pipeline)"
    description: "Openshift pipeline template"
    iconClass: "icon-jenkins"
    tags: "instant-app,jenkins"

parameters:
  - name: "APP_NAME"
    displayName: "THe name of the app, the build pipeline is for"
    required: true

  - name: "GIT_REPO"
    displayName: "The https url to the app's git repository"
    required: true

  - name: "GIT_REF"
    displayName: "The git ref of the repository to build"
    required: true

  - name: "JENKINS_FILE_PATH"
    displayName: "The fully qualified path to the Jenkinsfile"
    value: "Jenkinsfile"
    required: true

  - name: "SECRET_GITHUB_SSH"
    displayName: "The git secret to use"
    required: true

  - name: "SECRET_GITHUB_HOOK"
    displayName: "The git webhook secret to use"
    required: true

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "${APP_NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
      labels:
        name: "${APP_NAME}"
      name: "${APP_NAME}-pipe"
    spec:
      source:
        type: "Git"
        sourceSecret:
          - "${SECRET_GITHUB_SSH}"
        git:
          uri: "${GIT_REPO}"
          ref: "${GIT_REF}"
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: "${JENKINS_FILE_PATH}"
        type: JenkinsPipeline
      trigger:
          - type: "GitHub"
            github:
              secret: "${SECRET_GITHUB_HOOK}"
          - type: "ConfigChange"
