apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pipelines
kind: "Template"
apiVersion: "v1"
metadata:
  name: "jenkins-pipeline"
  annotations:
    openshift.io/display-name: "Jenkins (Pipeline)"
    description: "Openshift pipeline template"
    iconClass: "icon-jenkins"
    tags: "instant-app,jenkins"

parameters:
  - name: "APP_NAME"
    displayName: "THe name of the app, the build pipeline is for"
    required: true

  - name: "GIT_REPO"
    displayName: "The https url to the app's git repository"
    required: true

  - name: "GIT_REF"
    displayName: "The git ref of the repository to build"
    required: true

  - name: "JENKINS_FILE_PATH"
    displayName: "The fully qualified path to the Jenkinsfile"
    value: "Jenkinsfile"
    required: true

  - name: "MAVEN_MIRROR_URL"
    displayName: "The url of the maven mirror"
    required: true

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "${APP_NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
      labels:
        name: "${APP_NAME}"
      name: "${APP_NAME}"
    spec:
      source:
        type: "Git"
        sourceSecret:
          - "plosam-ssh"
        git:
          uri: "${GIT_REPO}"
          ref: "${GIT_REF}"
      strategy:
        jenkinsPipelineStrategy:
          env:
            - name: "APP_NAME"
              value: "${APP_NAME}"
            - name: "GIT_REPO"
              value: "${GIT_REPO}"
            - name: "GIT_REF"
              value: "${GIT_REF}"
            - name: "MAVEN_MIRROR_URL"
              value: "${MAVEN_MIRROR_URL}"
            - name: "GIT_SSL_NO_VERIFY"
              value: true
          jenkinsfilePath: "${JENKINS_FILE_PATH}"
        type: JenkinsPipeline
