apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pipelines
kind: "Template"
apiVersion: "v1"
metadata:
  name: "jenkins-pipeline"
  annotations:
    openshift.io/display-name: "Jenkins (Pipeline)"
    description: "Openshift pipeline template"
    iconClass: "icon-jenkins"
    tags: "instant-app,jenkins"

parameters:
  - name: "PIPE_NAME"
    displayName: "THe name of the pipeline"
    required: true

  - name: "APP_NAME"
    displayName: "THe name of the app, the build pipeline is for"
    required: true

  - name: "GIT_REPO"
    displayName: "The https url to the app's git repository"
    required: true

  - name: "GIT_REF"
    displayName: "The git ref of the repository to build"
    required: true

  - name: "JENKINS_FILE_PATH"
    displayName: "The fully qualified path to the Jenkinsfile"
    value: "Jenkinsfile"
    required: true

  - name: "SECRET_GITHUB_SSH"
    displayName: "The git secret to use"
    required: true

  - name: "SECRET_GITHUB_HOOK"
    displayName: "The git webhook secret to use"
    required: true

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: "${APP_NAME}"
      name: "${PIPE_NAME}"
    spec:
      triggers:
        - type: "GitHub"
          github:
            secret: "${SECRET_GITHUB_HOOK}"
        - type: "ConfigChange"
      source:
        type: "Git"
        git:
          uri: "${GIT_REPO}"
          ref: "${GIT_REF}"
        sourceSecret:
          - "${SECRET_GITHUB_SSH}"
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: "${JENKINS_FILE_PATH}"
        type: JenkinsPipeline
